spring:
  servlet:
    multipart:
      # 设置单个文件大小
      max-file-size: 1024MB
      # 单次请求文件大小
      max-request-size: 1024MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easypan?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678

server:
  port: 7090
  servlet:
    context-path: /api

image:
  default_avator :   ./src/main/resources/static/img/default_avator.png

file:
  desc: D:\sim-file\

